spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3307/websystique
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect