---
server:
  port: 8080
# contextPath: /SpringBootCRUDApp
spring:
  profiles:
    active: prod
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    org.hibernate.SQLQuery: INFO
   # file: logs/practice.log
    pattern:
      console: '%d{yyyy-MM-dd HH:mm:ss} %clr(%5p) %clr(%-40.40C{1}){blue} %clr(%-30.30M){magenta} %clr(%-3.5L){cyan} --- %m%n'
        # file: '%d{yyyy-MM-dd HH:mm:ss} %5p %-40.40C{1} %-30.30M %-3.5L --- %m%n'

output:
  ansi:
  enabled: DETECT

---
spring:
  application:
    name: spring-boot
  profiles: local, default
datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  sampleapp:
    url: jdbc:mysql://localhost:3307/websystique
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

